// ignore_for_file: unnecessary_string_escapes, equal_keys_in_map

import 'package:get/get.dart';

final class LocalString extends Translations {
  @override
  Map<String, Map<String, String>> get keys => {
        //ENGLISH LANGUAGE
        'en_US': {
        //NEW 
        "Good to see you again":"Good to see you again",
        "Welcome back to SIS. Let’s continue your journey!":"Welcome back to SIS. Let’s continue your journey!",
        "Enter Email Address":"Enter Email Address",
        "Enter Password":"Enter Password",
        "Forgot password?":"Forgot password?",
        "Sign In":"Sign In",
        "Continue with Google":"Continue with Google",
        "Don’t have an account?":"Don’t have an account?",
        "Register": "Register",
        "Please register to start your journey":"Please register to start your journey",
        "Welcome":"Welcome",
        "User Name":"User Name",
        "Email Address":"Email Address",
        "Password":"Password",
        "Confirm Password":"Confirm Password",
        "Confirm Password":"Confirm Password",
        "Already have an account?":"Already have an account?",
        "log In":"Log In",











          //Old 
          "Delivery Man Info": "Delivery Man Info",
          "Do you want to exit the app?": "Do you want to exit the app?",
          "No": "No",
          "Yes": "Yes",
          "You need to log in first": "You need to log in first",
          "Profile": "Profile",
          "Pedidos": "Requests",
          "Pedidos   ": "Requests  ",
          "Search": "Search",
          "Home": "Home",
          "ERROR": "ERROR",
          "Confirm order": "Confirm order",
          "Adicionar morada": "Add adress",
          "Name of the address": "Nome do Endereço",
          "Rua do Outeiro": "Rua do Outeiro",
          "Address": "Morada",
          "Are you sure?": "Are you sure?",
          "Phone Number": "Phone Number",
          "City": "Cidade",
          "1º direito": "1º direito",
          "Enter to walk": "Enter to walk",
          "Postal Code": "Código Postal",
          "Enter Port Number": "Enter Port Number",
          "Country": "País",
          "Enter City": "Enter City",
          "State": "Estado",
          "Endereço padrão": "Default address",
          "Gravar": "Record",
          "Something went wrong": "Something went wrong",
          "Login successfully done": "Login successfully done",
          "Redefine password": "Redefine password",
          "Password": "Password",
          "Retype Password": "Retype Password",
          "Code": "Code",
          "Forgot your password": "Forgot your password",
          "Email": "Email",

          "Or login with": "Or login with",
          "Create Account": "Create Account",
          "First Name": "First Name",
          "First Name Can't be empty": "First Name Can't be empty",
          "Your Name": "Your Name",
          "Last Name": "Last Name",
          "Last Name Can't be empty": "Last Name Can't be empty",
          "Phone": "Phone",
          "phone number can't empty": "Phone number can't be empty",
          "Email Can't be empty": "Email Can't be empty",
          "Password must be  at least 6 characters": "Password must be  at least 6 characters",
          "Confim Password": "Confim Password",
          "Password Missmatch": "Password Missmatch",
          "Terms and Conditions": "Terms and Conditions",
          "I agree with terms and conditions and privacy policy":
              "I agree with terms and conditions and privacy policy",
          "Please accept the terms & condition!": "Please accept the terms & condition!",
          "Please check your internet connection": "Please check your internet connection",
          "Please login to perform this operation": "Please login to perform this operation",
          "Verify Otp": "Verify Otp",
          "verify provided otp": "verify provided otp",
          "Aplicar códido": "Aply code",
          "Aplicar": "Apply",
          "Enter Voucher": "Enter Voucher",
          "Voucher must be  at least 6 characters": "Voucher must be  at least 6 characters",
          "Adicionar código promocional": "Add promotional code",
          "Carrinho": "Cart",
          "O Teu Pedido": "Your request",
          " produto de ": "product",
          "Morada de entrega": "Delivery address",
          "Schedule delivery": "Schedule delivery",
          "Selecione um dia e hora": "Select a day and a hour",
          "Alterar": "Change",
          "Voucher Aplicado": "Aplyed voucher",
          "Tens um código promocional?": "You have a promotional code",
          "Sumário": "Summary",
          "Produtos": "Product",
          "Entrega": "Delivary",
          "Embalagem": "Package",
          "Total": "Total",
          "ar pedido": " request",
          "Select delivery Time": "Select delivery Time",
          "Agendar": "Schedule",
          "Cancelar": "Cancel",
          "Extras": "Extras",
          "Not Available": "Not Available",
          "Can't add more then 5 extra item": "Can't add more then 5 extra item",
          "Categories": "Categories",
          "Em destaque": "Highlighted",
          "Os seu favoritos": "Your favorits",
          "Opções": "Options",
          "Special Request": "Special Request",
          "Adicionar": "Add",
          "Add address To contiinue browsing": "Add address To contiinue browsing",
          "Entregar em": "Delivery in ",
          "Pesquisa": "Search",
          "Closed": "Closed",
          "VER TODOS": "SEE ALL",
          "Currently Not Available": "Currently Not Available",
          "Pedido": "Request",
          "Detalhes do pedido": "Request details",
          "Código de estafeta": "Code of the delivery boy",
          "Horário de entrega": "Delivery time",
          "Estado da encomenda": "Order state ",
          "Em curso": "On going",
          "Histórico": "History",
          "Pedir novamente": "Ask again",
          "Detalhes": "Details",
          "Seguir": "Follow",
          "Checkout": "Checkout",
          "Pagamenta": "Payment",
          "Add card": "Adicionar cartão",
          "Pagar": "Pay",
          "Select Payment Method": "Select Payment Method",
          "Perfil": "Profile",
          "As minhas moradas": "My adresses",
          "Ver os meus pedidos": "See my requests",
          "Contacto": "Contact",
          "Informações pessoais": "Personal information",
          "Preferências": "Preferences",
          "Idioma atual": "Current language",
          "Ajuda": "Help",
          "Enviar mensagem": "Send Message",
          "Conta": "Account",
          "You won't be able to revert this!": "You won't be able to revert this!",
          "Delete My Account": "Delete My Account",
          "You are about to Logout!": "You are about to Logout!",
          "Terminar sessão": "Log out",
          "Send Message": "Send Message",
          "Enter subject": "Enter subject",
          "Enter message": "Enter message",
          "message must be  at least 15 characters": "message must be  at least 15 characters",
          "No file selected": "No file selected",
          "Enter Value": "Enter Value",
          "Pesquisar": "Search",
          "Enter text": "Enter text",
          "Principais categorias": "Main categories",
          "Todas as categorias": "All categories",
          "Please select address from map": "Please select address from map",
          "Delivery Status": "Delivery Status",
          "Enter Address name": "Enter Address name",
          "Enter Address": "Enter Address",
          "Enter Postal Code": "Enter Postal Code",
          "Name on the card": "Name on the card",
          "Card Number": "Card Number",
          "Enter Card Name": "Enter Card Name",
          "Data de validade": "Expiration date",
          "Enter Expiry Date": "Enter Expiry Date",
          "Cartão padrão": "Standard card",
          "Cartão 1": "Card 1",
          "Old Password": "Old Password",
          "Enter oldPassword": "Enter oldPassword",
          "miss match old password": "miss match old password",
          "New Password": "New Password",
          "Enter newpassword": "Enter newpassword",
          "password must be 5 character": "password must be 5 character",
          " Password": " Password",
          "password not matched": "password not matched",
          "Andar": "To Walk",
          "Enter email": "Enter email",
          "email must be  at least 6 characters": "email must be  at least 6 characters",
          "NIF": "NIF",
          "Enter nif": "Enter nif",
          "nif must be  at least 6 characters": "nif must be  at least 6 characters",
          "Enter phone": "Enter phone",
          "phone must be  at least 6 characters": "phone must be  at least 6 characters",
          "Email": "Email",
          "Hoje": "Today",
          "Amanha": "Tomorrow",
          "Data connection is available.": "Data connection is available.",
          "You are not logged in": "You are not logged in",
          " minutes": " minutes",
          " unidades": " units",
          "Confirm Password": "Confirm Password",
          "Confirmed": "Confirmed",
          "Delivery Started": "Delivery Started",
          "Arrived at Shop": "Arrived at Shop",
          "Transit": "Transit",
          "Delivered": "Delivered",
          "On Transit": "On Transit",
          "ORDER FOR LATER": "ORDER FOR LATER",
          "OPEN NOW": "OPEN NOW",
          "This shop is closed now!": "This shop is closed now!",
          "Items": "Items",
          "Success": "Success",
          "Success with no content": "Success with no content",
          "Bad request. Try again later": "Bad request. Try again later",
          "User unauthorized. Try again later": "User unauthorized. Try again later",
          "Forbidden request. Try again later": "Forbidden request. Try again later",
          "Something went wrong. Try again later": "Something went wrong. Try again later",
          "URL not found. Try again later": "URL not found. Try again later",
          "Timeout. Try again later": "Timeout. Try again later",
          "Request canceled": "Request canceled",
          "Timeout. Try again later": "Timeout. Try again later",
          "Cache error. Try again later": "Cache error. Try again later",
          "Please check your internet connection": "Please check your internet connection",
          "Something went wrong": "Something went wrong",
        },



       
      };
}
